# Generated by Django 4.1.5 on 2023-03-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiellib', models.CharField(max_length=30)),
                ('materieldesc', models.CharField(max_length=150)),
                ('materieldatearrivee', models.DateField()),
                ('materieldatecreation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertypeLib', models.CharField(max_length=30)),
                ('usertypedesc', models.CharField(max_length=200)),
                ('usertypedatecreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstname', models.CharField(max_length=30, unique=True)),
                ('userLastname', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userNumber', models.IntegerField()),
                ('userdatecreation', models.DateTimeField(auto_now=True)),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
        ),
    ]
